Blog app - Views
Bornittah/rails-blog-app pull request #6
Opened 2023-03-17 15:11 UTC by Bornittah

**Summary**

- [ ] Implement the design from the sneak peek wireframe
| ![image](https://user-images.githubusercontent.com/31854631/225941735-f9a7e2d4-5f7d-4e08-b4b6-60d826cf5ac5.png) | ![image](https://user-images.githubusercontent.com/31854631/225941824-e80ffbdc-d929-4527-893f-53e0ebd7daa4.png)
![image](https://user-images.githubusercontent.com/31854631/225941892-49f95c5c-f954-4027-8b4a-08bd98328ca7.png) | ![image](https://user-images.githubusercontent.com/31854631/225941943-5fc40427-3ceb-41a4-adde-14eb8ad38551.png)|

2023-03-17 17:40 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @Bornittah 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow Gitflow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-17 17:40 UTC, tresorsawasawa commented on app/views/users/show.html.erb
> +      </li>
- [ ] Kindly make sure you use `#three_recent_posts` method to render the **user's 3 most recent post** as require for the project and to match the required the given [wireframe format](https://github.com/microverseinc/curriculum-rails/raw/main/blog-app/images/blog_user_page.png).

2023-03-17 17:40 UTC, tresorsawasawa commented on app/views/users/index.html.erb
> +    </li>
- [ **OPTIONAL** ] I think it would be better if you use `partial` file for one `User` card for best practices and DRY rules. I suggest you refer this **[article](https://guides.rubyonrails.org/layouts_and_rendering.html#using-partials)** to help you how to do it and more details about partial files.

2023-03-17 17:40 UTC, tresorsawasawa commented on app/views/users/show.html.erb
> +    </li>
- [ **OPTIONAL** ] I think it would be better if you use `partial` file for one `User` card for best practices and DRY rules. I suggest you refer this **[article](https://guides.rubyonrails.org/layouts_and_rendering.html#using-partials)** to help you how to do it and more details about partial files.

2023-03-17 17:40 UTC, tresorsawasawa commented on app/views/posts/index.html.erb
> +    </li>
- [ **OPTIONAL** ] I think it would be better if you use `partial` file for one `User` card for best practices and DRY rules. I suggest you refer this **[article](https://guides.rubyonrails.org/layouts_and_rendering.html#using-partials)** to help you how to do it and more details about partial files.

2023-03-17 17:40 UTC, tresorsawasawa commented on app/views/posts/index.html.erb
> +        </ul>
- [ **OPTIONAL** ] I think it would be better if you use `partial` file for one `Post` card for best practices and DRY rules. I suggest you refer this **[article](https://guides.rubyonrails.org/layouts_and_rendering.html#using-partials)** to help you how to do it and more details about partial files.
I suggest you apply this approach every where you want to use `Post` and `User` cards code.

2023-03-17 17:40 UTC, tresorsawasawa commented on app/views/users/show.html.erb
> +  </div>
- [ ] As required for the project, kindly make sure when the user clicks the `See all Posts` link/button, it opens user's post index(i.e. `app/views/posts/index.html.erb` page) as displayed on the [wireframe](https://github.com/microverseinc/curriculum-rails/raw/main/blog-app/images/blog_user_all_posts.png)

2023-03-17 17:40 UTC, tresorsawasawa commented on app/controllers/posts_controller.rb
> +  end
- [ ] Kindly make sure you correct this above typo error as your app raises the  below error when trying to visit the `app/views/posts/index.html.erb` page
![Screenshot from 2023-03-17 19-10-46](https://user-images.githubusercontent.com/83042742/225972846-1ea74736-234c-44a0-8adb-68bcf50d4ead.png)

```ruby
  # Good
    ...
    @posts = @user.posts
  end

2023-03-17 17:40 UTC, tresorsawasawa commented on app/views/posts/index.html.erb
> +        <% end %>
- [ ] As a comment belongs to an `author`, kindly make sure you also update the above line by using the `author` key word, else where you'll find another error when running your app. i.e.
```ruby
  ...
  <li><%= comment.author.name %><%= comment.text %></li>
  ...
```

2023-03-17 17:40 UTC, tresorsawasawa commented on app/views/posts/show.html.erb
> +</div>
- [ ] As required for the project, Kindly ensure that the Post show page displays post with all comments listed as shown on the [wireframe](https://github.com/microverseinc/curriculum-rails/raw/main/blog-app/images/blog_single_post.png). For that, I also suggest when a user clicks on a `Post` it redirects to its `show` page. 
Right now, if the user opens the `Post show page`, your app displays the below error. **Make sure you check how you implemented the `Show` action from your `PostsController`**, change in your views where you use `user` keyword to `author` as `comments` and `posts` belong to an `author` and then fix this error :point_down: :point_down: 
![Screenshot from 2023-03-17 19-27-09](https://user-images.githubusercontent.com/83042742/225976079-7c05b3a0-7794-4927-9e5e-d6a7b1e880a8.png)

2023-03-18 12:56 UTC, brytebee approved these changes
Hi, @Bornittah👋,

##

### Highlights💡
- Good commit message.✔️ 
- Good PR Summary.✔️
- Great UI design.✔️
- App functions as it should.✔️
- Great implementing the suggested changes.✔️

##

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![](https://media.giphy.com/media/fxsqOYnIMEefC/giphy.gif)

Good luck! 🎉 

##

###  **Optional Suggestions:**
- N/A

------

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-18 17:08 UTC, merged